### ISSUE TITLE
nsd failed to start after enabling chroot

### ISSUE THREAD

**Issue by eshankar43** [NLnetLabs/nsd#214] opened 2022-04-14 12:13 UTC
Hi,

we are running working nsd setup on version 4.3.8. however when i enable chroot the nsd daemon fails to start.  once i disable chroot the daemons comes up with out any issue.

find below the error messages.  unable to troubleshoot as the error message also not clear.

Apr 14 15:56:36 lvendnsath002u systemd[1]: nsd.service: Succeeded.
Apr 14 15:56:36 lvendnsath002u systemd[1]: Stopped NSD DNS Server.
Apr 14 15:56:36 lvendnsath002u systemd[1]: Starting NSD DNS Server...
Apr 14 15:56:36 lvendnsath002u systemd[1]: Started NSD DNS Server.
Apr 14 15:57:18 lvendnsath002u systemd[1]: Stopping NSD DNS Server...
Apr 14 15:57:18 lvendnsath002u systemd[1]: nsd.service: Succeeded.
Apr 14 15:57:18 lvendnsath002u systemd[1]: Stopped NSD DNS Server.
Apr 14 15:57:18 lvendnsath002u systemd[1]: Starting NSD DNS Server...
Apr 14 15:58:49 lvendnsath002u systemd[1]: nsd.service: start operation timed out. Terminating.
Apr 14 15:58:49 lvendnsath002u systemd[1]: nsd.service: Failed with result 'timeout'.
Apr 14 15:58:49 lvendnsath002u systemd[1]: Failed to start NSD DNS Server.

also find below my configuration.

++++++++++++++++++++
server:
  server-count: 2
  ip-address: x.x.x.x
  ip-address: x.x.x.x
  zonesdir: /etc/nsd/zones/
  identity: "Check Check"
  ip4-only: "yes"
  verbosity: "5"

  username: nsd
  chroot: /etc/nsd
  database: /etc/nsd/db/nsd.db
  pidfile: /etc/nsd/run/nsd.pid
  zonelistfile: /etc/nsd/db/zone.list
  xfrdfile: /etc/nsd/run/ixfr.state
  xfrdir: /etc/nsd/run/xfr
  logfile: /etc/nsd/log/nsdlog.log

#harden parameters from security
  do-ip6: no
  hide-version: yes
  hide-identity: yes
  drop-updates: yes
  refuse-any: yes
  answer-cookie: yes
##
remote-control:
        control-enable: yes
        control-port: 8952
        control-interface: x.x.x.x
pattern:
        name: master
include: "/etc/nsd/conf.d/zone.conf"
+++++++++++++++++++++++++++++

appreciate any help to fix the issue.

Rgds / shankar.

**Comment by wcawijngaards** [comment] 2022-04-14 12:39
The error messages you post are from the systemd, you need to see the nsd error messages. You made nsd log to the nsdlog.log file.

You could also look at the output of nsd-checkconf, it may printout what is wrong. Or start NSD, briefly, from the commandline, with -d option to stay attached to that console. It can then print error messages that happen before it starts printing to the logfile, to the console.

**Comment by eshankar43** [comment] 2022-04-15 05:59
hi @wcawijngaards,

NSD log is also not showing any message, simply prints shutting down.

find below the fresh logs taken after enabling chroot.
=========================================
NSD Log:

 [2022-04-15 09:33:32.721] nsd[4123262]: warning: signal received, shutting down...
[2022-04-15 09:33:32.769] nsd[4123707]: notice: nsd starting (NSD 4.3.8)
[2022-04-15 09:33:32.769] nsd[4123707]: notice: listen on ip-address 127.0.0.1@53 (udp) with server(s): *
[2022-04-15 09:33:32.769] nsd[4123707]: notice: listen on ip-address 127.0.0.1@53 (tcp) with server(s): *
[2022-04-15 09:33:32.769] nsd[4123707]: notice: listen on ip-address 10.119.10.247@53 (udp) with server(s): *
[2022-04-15 09:33:32.769] nsd[4123707]: notice: listen on ip-address 10.119.10.247@53 (tcp) with server(s): *
[2022-04-15 09:33:32.888] nsd[4123708]: info: zone 10.in-addr.arpa read with success
[2022-04-15 09:33:32.912] nsd[4123708]: info: zone 10.in-addr.arpa written to db
[2022-04-15 09:33:32.922] nsd[4123708]: info: zone 172.in-addr.arpa read with success
[2022-04-15 09:33:32.929] nsd[4123708]: info: zone 172.in-addr.arpa written to db
[2022-04-15 09:33:32.932] nsd[4123708]: info: zone 192.in-addr.arpa read with success
[2022-04-15 09:33:32.935] nsd[4123708]: info: zone 192.in-addr.arpa written to db
[2022-04-15 09:33:32.935] nsd[4123708]: info: zone eiuat.com read with success
[2022-04-15 09:33:32.936] nsd[4123708]: info: zone eiuat.com written to db
[2022-04-15 09:33:32.937] nsd[4123708]: info: zone ocp4.emiratesnbd.com read with success
[2022-04-15 09:33:32.937] nsd[4123708]: info: zone ocp4.emiratesnbd.com written to db
[2022-04-15 09:33:32.942] nsd[4123708]: info: zone enbduat.com read with success
[2022-04-15 09:33:32.951] nsd[4123708]: info: zone enbduat.com written to db
[2022-04-15 09:33:32.951] nsd[4123708]: info: zone shankare.com read with success
[2022-04-15 09:33:32.951] nsd[4123708]: info: zone shankare.com written to db
[2022-04-15 09:33:32.952] nsd[4123708]: info: zone shanker.com read with success
[2022-04-15 09:33:32.952] nsd[4123708]: info: zone shanker.com written to db
[2022-04-15 09:33:32.952] nsd[4123708]: info: zone sseb.com read with success
[2022-04-15 09:33:32.952] nsd[4123708]: info: zone sseb.com written to db
[2022-04-15 09:33:32.953] nsd[4123708]: notice: nsd started (NSD 4.3.8), pid 4123707
[2022-04-15 09:35:02.860] nsd[4123708]: warning: signal received, shutting down...
=========================================

systemd output:

[root@lvendnsath002u nsd]# systemctl restart nsd
Job for nsd.service failed because a timeout was exceeded.
See "systemctl status nsd.service" and "journalctl -xe" for details.
[root@lvendnsath002u nsd]# systemctl status nsd
● nsd.service - NSD DNS Server
   Loaded: loaded (/usr/lib/systemd/system/nsd.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Fri 2022-04-15 09:35:02 +04; 19s ago
  Process: 4123707 ExecStart=/usr/sbin/nsd -d -c /etc/nsd/nsd.conf $NSD_EXTRA_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 4123707 (code=exited, status=0/SUCCESS)

Apr 15 09:33:32 lvendnsath002u systemd[1]: nsd.service: Succeeded.
Apr 15 09:33:32 lvendnsath002u systemd[1]: Stopped NSD DNS Server.
Apr 15 09:33:32 lvendnsath002u systemd[1]: Starting NSD DNS Server...
Apr 15 09:35:02 lvendnsath002u systemd[1]: nsd.service: start operation timed out. Terminating.
Apr 15 09:35:02 lvendnsath002u systemd[1]: nsd.service: Failed with result 'timeout'.
Apr 15 09:35:02 lvendnsath002u systemd[1]: Failed to start NSD DNS Server.
[root@lvendnsath002u nsd]#

nsd -d is not showing any error, i tried to run some nsd-control commands and they were giving the outputs.
===========================================
[root@lvendnsath002u log]# nsd -d
[2022-04-15 09:47:10.296] nsd[4124950]: notice: nsd starting (NSD 4.3.8)
[2022-04-15 09:47:10.296] nsd[4124950]: notice: listen on ip-address 127.0.0.1@53 (udp) with server(s): *
[2022-04-15 09:47:10.296] nsd[4124950]: notice: listen on ip-address 127.0.0.1@53 (tcp) with server(s): *
[2022-04-15 09:47:10.296] nsd[4124950]: notice: listen on ip-address 10.119.10.247@53 (udp) with server(s): *
[2022-04-15 09:47:10.296] nsd[4124950]: notice: listen on ip-address 10.119.10.247@53 (tcp) with server(s): *
[2022-04-15 09:47:10.419] nsd[4124951]: info: zone 10.in-addr.arpa read with success
[2022-04-15 09:47:10.448] nsd[4124951]: info: zone 10.in-addr.arpa written to db
[2022-04-15 09:47:10.459] nsd[4124951]: info: zone 172.in-addr.arpa read with success
[2022-04-15 09:47:10.467] nsd[4124951]: info: zone 172.in-addr.arpa written to db
[2022-04-15 09:47:10.471] nsd[4124951]: info: zone 192.in-addr.arpa read with success
[2022-04-15 09:47:10.474] nsd[4124951]: info: zone 192.in-addr.arpa written to db
[2022-04-15 09:47:10.475] nsd[4124951]: info: zone eiuat.com read with success
[2022-04-15 09:47:10.475] nsd[4124951]: info: zone eiuat.com written to db
[2022-04-15 09:47:10.477] nsd[4124951]: info: zone ocp4.emiratesnbd.com read with success
[2022-04-15 09:47:10.477] nsd[4124951]: info: zone ocp4.emiratesnbd.com written to db
[2022-04-15 09:47:10.480] nsd[4124951]: info: zone enbduat.com read with success
[2022-04-15 09:47:10.490] nsd[4124951]: info: zone enbduat.com written to db
[2022-04-15 09:47:10.490] nsd[4124951]: info: zone shankare.com read with success
[2022-04-15 09:47:10.491] nsd[4124951]: info: zone shankare.com written to db
[2022-04-15 09:47:10.491] nsd[4124951]: info: zone shanker.com read with success
[2022-04-15 09:47:10.491] nsd[4124951]: info: zone shanker.com written to db
[2022-04-15 09:47:10.491] nsd[4124951]: info: zone sseb.com read with success
[2022-04-15 09:47:10.491] nsd[4124951]: info: zone sseb.com written to db
[2022-04-15 09:47:10.492] nsd[4124951]: notice: nsd started (NSD 4.3.8), pid 4124950

[2022-04-15 09:52:57.260] nsd[4124950]: info: new control connection from 10.119.10.247
[2022-04-15 09:52:57.284] nsd[4124950]: info: remote control connection authenticated
[2022-04-15 09:52:57.284] nsd[4124950]: info: control cmd:  status
[2022-04-15 09:52:57.284] nsd[4124950]: info: remote control operation completed
[2022-04-15 09:53:07.197] nsd[4124950]: info: new control connection from 10.119.10.247
[2022-04-15 09:53:07.213] nsd[4124950]: info: remote control connection authenticated
[2022-04-15 09:53:07.213] nsd[4124950]: info: control cmd:  stats
[2022-04-15 09:53:07.231] nsd[4124950]: info: remote control stats printed
[2022-04-15 09:53:48.701] nsd[4124950]: info: new control connection from 10.119.10.247
[2022-04-15 09:53:48.723] nsd[4124950]: info: remote control connection authenticated
[2022-04-15 09:53:48.723] nsd[4124950]: info: control cmd:  zonestatus enbduat.com
[2022-04-15 09:53:48.723] nsd[4124950]: info: remote control operation completed
[2022-04-15 09:54:03.692] nsd[4124950]: info: new control connection from 10.119.10.247
[2022-04-15 09:54:03.709] nsd[4124950]: info: remote control connection authenticated
[2022-04-15 09:54:03.709] nsd[4124950]: info: control cmd:  serverpid
[2022-04-15 09:54:03.709] nsd[4124950]: info: remote control operation completed

===========
[root@lvendnsath002u nsd]# nsd-control serverpid
4124951
[root@lvendnsath002u nsd]# nsd-control status
version: 4.3.8
verbosity: 5
ratelimit: 200
[root@lvendnsath002u nsd]#

===================================

**Comment by wcawijngaards** [comment] 2022-04-20 11:52
Since the commandline start works fine, it is not an issue with the configuration or the software itself. That is working fine. Something is wrong when you start it with systemd. That depends on your systemd setup and scripts. Those are from the package that you installed, and are not actually created here. The packagers add the systemd integration files.

You would figure that the issue is then in `/usr/lib/systemd/system/nsd.service;` or something else that reacts to the NSD start, and then you have to find out where the signal that is sent to stop NSD is coming from.

When you run multiple NSDs you have to run them with separate pid files. NSD tries to kill the previous server, if that still exists, if you try to start it twice, I believe.

**Comment by k0ekk0ek** [comment] 2022-12-02 11:08
@eshankar43, I'm going to assume that your questions have been answered and closing the issue. If you still have questions, feel free to reopen or create a new issue.

**Closed as completed by k0ekk0ek** 2022-12-02 11:08 UTC
